--------------------------------------------------------
--  File created - Monday-March-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_BLOG_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_BLOG_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_COMMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_COMMENT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_NOTIFICATION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_NOTIFICATION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_PAYMENT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_PAYMENT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_REPORT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_REPORT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_SCAN_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_SCAN_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_SUBSCRIPTION_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_SUBSCRIPTION_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_USER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_USER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQUENCE_VULNERABILITY_ID
--------------------------------------------------------

   CREATE SEQUENCE  "BUG_DETECTOR"."SEQUENCE_VULNERABILITY_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BLOG
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."BLOG" 
   (	"BLOG_ID" NUMBER, 
	"TITLE" VARCHAR2(255 BYTE), 
	"CONTENT" CLOB, 
	"PUBLICATION_DATE" DATE DEFAULT sysdate, 
	"CATEGORY_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"LIKE_NUMBER" NUMBER DEFAULT 0, 
	"DISLIKE_NUMBEW" NUMBER DEFAULT 0
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."COMMENTS" 
   (	"COMMENT_ID" NUMBER, 
	"CONTENT" CLOB, 
	"PUBLICATION_DATE" DATE DEFAULT sysdate, 
	"BLOG_ID" NUMBER, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."NOTIFICATION" 
   (	"NOTIFICATION_ID" NUMBER, 
	"SENT_DATE" DATE DEFAULT sysdate, 
	"MASSAGE" CLOB, 
	"NOTIFICATION_TYPE" VARCHAR2(255 BYTE), 
	"TYPE_ID" NUMBER, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("MASSAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."PAYMENT" 
   (	"PAYMENT_ID" NUMBER DEFAULT NULL, 
	"PAYMENT_STATUS" VARCHAR2(255 BYTE), 
	"USER_ID" NUMBER, 
	"PAYMENT_NUMDER" VARCHAR2(16 BYTE), 
	"CVV" VARCHAR2(3 BYTE), 
	"EXPAIR_DATE" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPORT
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."REPORT" 
   (	"REPORT_ID" NUMBER, 
	"REPORT_FILE" VARCHAR2(255 BYTE), 
	"USER_ID" NUMBER, 
	"SCAN_ID" NUMBER, 
	"TYPE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCAN
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."SCAN" 
   (	"SCAN_ID" NUMBER, 
	"STATUS" VARCHAR2(255 BYTE), 
	"TARGET" VARCHAR2(255 BYTE), 
	"CREATED_AT" DATE DEFAULT sysdate, 
	"SCHEDLE" DATE, 
	"USER_ID" NUMBER, 
	"TYPE" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIPTION
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."SUBSCRIPTION" 
   (	"SUBSCRIPTION_ID" NUMBER, 
	"SUBSCRIPTION_PLAN" VARCHAR2(20 BYTE), 
	"EXPIRY_DATE" TIMESTAMP (6), 
	"PAYMENT_ID" NUMBER, 
	"USER_ID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."USER_INFO" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VULNERABILITY
--------------------------------------------------------

  CREATE TABLE "BUG_DETECTOR"."VULNERABILITY" 
   (	"VULNERABILITY_ID" NUMBER, 
	"DESCRIPTION" CLOB, 
	"VULNERABILITY_TYPE" VARCHAR2(255 BYTE), 
	"MITIGATION" CLOB, 
	"SEVERITY" VARCHAR2(255 BYTE), 
	"IMPACT" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("MITIGATION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("IMPACT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into BUG_DETECTOR.BLOG
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.COMMENTS
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.NOTIFICATION
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.PAYMENT
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.REPORT
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.SCAN
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.SUBSCRIPTION
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.USER_INFO
SET DEFINE OFF;
REM INSERTING into BUG_DETECTOR.VULNERABILITY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index VULNERABILITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."VULNERABILITY_PK" ON "BUG_DETECTOR"."VULNERABILITY" ("VULNERABILITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PAYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."PAYMENT_PK" ON "BUG_DETECTOR"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEB_SCAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."WEB_SCAN_PK" ON "BUG_DETECTOR"."SCAN" ("SCAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BLOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."BLOG_PK" ON "BUG_DETECTOR"."BLOG" ("BLOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOTIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."NOTIFICATION_PK" ON "BUG_DETECTOR"."NOTIFICATION" ("NOTIFICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WEB_REPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."WEB_REPORT_PK" ON "BUG_DETECTOR"."REPORT" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_INFO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."USER_INFO_UK1" ON "BUG_DETECTOR"."USER_INFO" ("USER_NAME", "USER_ID", "EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VULNERABILITY_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."VULNERABILITY_UK1" ON "BUG_DETECTOR"."VULNERABILITY" ("VULNERABILITY_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."USER_INFO_PK" ON "BUG_DETECTOR"."USER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."COMMENTS_PK" ON "BUG_DETECTOR"."COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBSCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BUG_DETECTOR"."SUBSCRIPTION_PK" ON "BUG_DETECTOR"."SUBSCRIPTION" ("SUBSCRIPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_BLOG_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_BLOG_ID" 
BEFORE INSERT ON BLOG
FOR EACH ROW
BEGIN
    SELECT sequence_BLOG_id.nextval
    INTO :NEW.BLOG_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_BLOG_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_COMMENT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_COMMENT_ID" 
BEFORE INSERT ON COMMENTS
FOR EACH ROW
BEGIN
    SELECT sequence_COMMENT_id.nextval
    INTO :NEW.COMMENT_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_COMMENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_NOTIFICATION_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_NOTIFICATION_ID" 
BEFORE INSERT ON NOTIFICATION
FOR EACH ROW
BEGIN
    SELECT sequence_NOTIFICATION_id.nextval
    INTO :NEW.NOTIFICATION_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_NOTIFICATION_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_PAYMENT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_PAYMENT_ID" 
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    SELECT SEQUENCE_PAYMENT_ID.nextval
    INTO :NEW.PAYMENT_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_PAYMENT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_REPORT_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_REPORT_ID" 
BEFORE INSERT ON REPORT
FOR EACH ROW
BEGIN
    SELECT sequence_REPORT_id.nextval
    INTO :NEW.REPORT_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_REPORT_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SCAN_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_SCAN_ID" 
BEFORE INSERT ON SCAN
FOR EACH ROW
BEGIN
    SELECT sequence_SCAN_id.nextval
    INTO :NEW.SCAN_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_SCAN_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_SUBSCRIPTION_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_SUBSCRIPTION_ID" 
BEFORE INSERT ON SUBSCRIPTION
FOR EACH ROW
BEGIN
    SELECT sequence_SUBSCRIPTION_id.nextval
    INTO :NEW.SUBSCRIPTION_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_SUBSCRIPTION_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_USER_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_USER_ID" 
BEFORE INSERT ON USER_INFO
FOR EACH ROW
BEGIN
    SELECT sequence_USER_id.nextval
    INTO :NEW.USER_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_USER_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER_VULNERABILITY_ID
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "BUG_DETECTOR"."TRIGGER_VULNERABILITY_ID" 
BEFORE INSERT ON VULNERABILITY
FOR EACH ROW
BEGIN
    SELECT sequence_VULNERABILITY_id.nextval
    INTO :NEW.VULNERABILITY_ID
    FROM dual;
END;
/
ALTER TRIGGER "BUG_DETECTOR"."TRIGGER_VULNERABILITY_ID" ENABLE;
--------------------------------------------------------
--  Constraints for Table SCAN
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("SCAN_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("TARGET" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SCAN" ADD CONSTRAINT "WEB_SCAN_PK" PRIMARY KEY ("SCAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."SCAN" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("NOTIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("SENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("MASSAGE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("NOTIFICATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_PK" PRIMARY KEY ("NOTIFICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBSCRIPTION
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" MODIFY ("SUBSCRIPTION_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" MODIFY ("SUBSCRIPTION_PLAN" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_PK" PRIMARY KEY ("SUBSCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."REPORT" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."REPORT" MODIFY ("REPORT_FILE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."REPORT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."REPORT" MODIFY ("SCAN_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."REPORT" ADD CONSTRAINT "WEB_REPORT_PK" PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."REPORT" MODIFY ("TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" MODIFY ("PUBLICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" MODIFY ("BLOG_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_INFO
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" ADD CONSTRAINT "USER_INFO_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" ADD CONSTRAINT "USER_INFO_UK1" UNIQUE ("USER_NAME", "USER_ID", "EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."USER_INFO" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BLOG
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("BLOG_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("PUBLICATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" ADD CONSTRAINT "BLOG_PK" PRIMARY KEY ("BLOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("LIKE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."BLOG" MODIFY ("DISLIKE_NUMBEW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("PAYMENT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("PAYMENT_NUMDER" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" ADD CONSTRAINT "PAYMENT_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("CVV" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."PAYMENT" MODIFY ("EXPAIR_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VULNERABILITY
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("VULNERABILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("VULNERABILITY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("MITIGATION" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("SEVERITY" NOT NULL ENABLE);
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" ADD CONSTRAINT "VULNERABILITY_PK" PRIMARY KEY ("VULNERABILITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" ADD CONSTRAINT "VULNERABILITY_UK1" UNIQUE ("VULNERABILITY_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUG_DETECTOR"."VULNERABILITY" MODIFY ("IMPACT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BLOG
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."BLOG" ADD CONSTRAINT "BLOG_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
  ALTER TABLE "BUG_DETECTOR"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK2" FOREIGN KEY ("BLOG_ID")
	  REFERENCES "BUG_DETECTOR"."BLOG" ("BLOG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."PAYMENT" ADD CONSTRAINT "PAYMENT_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPORT
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."REPORT" ADD CONSTRAINT "WEB_REPORT_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
  ALTER TABLE "BUG_DETECTOR"."REPORT" ADD CONSTRAINT "WEB_REPORT_FK2" FOREIGN KEY ("SCAN_ID")
	  REFERENCES "BUG_DETECTOR"."SCAN" ("SCAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCAN
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."SCAN" ADD CONSTRAINT "WEB_SCAN_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBSCRIPTION
--------------------------------------------------------

  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_FK1" FOREIGN KEY ("PAYMENT_ID")
	  REFERENCES "BUG_DETECTOR"."PAYMENT" ("PAYMENT_ID") ENABLE;
  ALTER TABLE "BUG_DETECTOR"."SUBSCRIPTION" ADD CONSTRAINT "SUBSCRIPTION_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "BUG_DETECTOR"."USER_INFO" ("USER_ID") ENABLE;
